//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItems
    {
        public int InvoiceItemId { get; set; }
        public int InvoiceId { get; set; }
        public int ItemNo { get; set; }
        public string NameSnapshot { get; set; }
        public Nullable<decimal> PotSizeSnapshot { get; set; }
        public Nullable<decimal> HeightSnapshot { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPriceSnapshot { get; set; }
        public decimal TaxRateSnapshot { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<int> SourceOrderItemId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual OrderItems OrderItems { get; set; }
    }
}
