//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceParties
    {
        public int InvoicePartyId { get; set; }
        public int InvoiceId { get; set; }
        public string Name { get; set; }
        public string TaxId { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public bool IsActive { get; set; }
        public string Country { get; set; }
    
        public virtual Invoices Invoices { get; set; }
    }
}
