//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Invoices = new HashSet<Invoices>();
            this.OrderItems = new HashSet<OrderItems>();
            this.Carriers = new HashSet<Carriers>();
        }
    
        public int OrderId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime PreparationDate { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int DeliveryAddressId { get; set; }
        public string SalesPerson { get; set; }
        public string Status { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string DeletedBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CarrierTypeId { get; set; }
    
        public virtual Addresses Addresses { get; set; }
        public virtual CarrierTypes CarrierTypes { get; set; }
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoices> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carriers> Carriers { get; set; }
    }
}
