//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMovements
    {
        public int StockMovementId { get; set; }
        public int StockItemId { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public string MovementType { get; set; }
        public decimal Quantity { get; set; }
        public decimal StockBefore { get; set; }
        public decimal StockAfter { get; set; }
        public System.DateTime MovementDate { get; set; }
        public string Reference { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string RemovedBy { get; set; }
        public Nullable<System.DateTime> RemovedAt { get; set; }
    
        public virtual OrderItems OrderItems { get; set; }
        public virtual StockItems StockItems { get; set; }
    }
}
