//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockItems()
        {
            this.OrderItems = new HashSet<OrderItems>();
            this.StockMovements = new HashSet<StockMovements>();
        }
    
        public int StockItemId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> GrowerId { get; set; }
        public Nullable<int> TrayTypeId { get; set; }
        public Nullable<int> QualityId { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public string InternalNo { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public Nullable<bool> IsInside { get; set; }
        public string FlowType { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string Remarks { get; set; }
    
        public virtual Growers Growers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Products Products { get; set; }
        public virtual Qualities Qualities { get; set; }
        public virtual TrayTypes TrayTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMovements> StockMovements { get; set; }
    }
}
